FROM ubuntu:latest
RUN apt-get update 

# Supervisor
RUN apt-get install supervisor golang-go -y

# Go
# RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz


# Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Worker layer

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./receive/receive.go


# Supervisord configuration
COPY worker.supervisor.toml /etc/supervisor/conf.d/supervisord.conf

# Run supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
