# Use a Go base image
FROM golang:1.24.1-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum to cache dependencies
COPY go.mod go.sum ./

# Download all dependencies. Caching will improve build times.
RUN go mod download

# Copy the source from the current directory to the working directory inside the container
COPY . .

# Build the Go application
RUN go build -o worker ./receive/receive.go

# Command to run when the container starts
CMD ["./worker"]